package com.example.aikeyboard.text

import com.example.aikeyboard.text.composing.Composer

class PinyinComposer : Composer {
    override val id = "pinyin"
    override val label = "Pinyin"
    override val toRead = 10

    // Pinyin to Chinese character mapping - Sắp xếp theo độ dài giảm dần để ưu tiên từ dài hơn
    private val pinyinToChinese = mapOf(
        "gonggongqiche" to "公共汽车",
        "shijiazhuang" to "石家庄",
        "zhongqiujie" to "中秋节",
        "qingmingjie" to "清明节",
        "hulianwang" to "互联网",
        "nanpengyou" to "男朋友",
        "guangzhou" to "广州",
        "chongqing" to "重庆",
        "zhengzhou" to "郑州",
        "changchun" to "长春",
        "huhehaote" to "呼和浩特",
        "duanwujie" to "端午节",
        "nvpengyou" to "女朋友",
        "zixingche" to "自行车",
        "meiwenti" to "没问题",
        "ruanjian" to "软件",
        "yingjian" to "硬件",
        "wangzhan" to "网站",
        "zhongguo" to "中国",
        "shanghai" to "上海",
        "shenzhen" to "深圳",
        "hangzhou" to "杭州",
        "changsha" to "长沙",
        "nanchang" to "南昌",
        "yinchuan" to "银川",
        "shenyang" to "沈阳",
        "zaoshang" to "早上",
        "wanshang" to "晚上",
        "mingtian" to "明天",
        "nianling" to "年龄",
        "xuesheng" to "学生",
        "shuijiao" to "水饺",
        "miantiao" to "面条",
        "shangxin" to "伤心",
        "yueliang" to "月亮",
        "xingxing" to "星星",
        "motuoche" to "摩托车",
        "chuzuche" to "出租车",
        "zaijian" to "再见",
        "duibuqi" to "对不起",
        "dianhua" to "电话",
        "duanxin" to "短信",
        "diannao" to "电脑",
        "wangluo" to "网络",
        "chengxu" to "程序",
        "shujuku" to "数据库",
        "youjian" to "邮件",
        "luyouqi" to "路由器",
        "beijing" to "北京",
        "nanjing" to "南京",
        "chengdu" to "成都",
        "tianjin" to "天津",
        "qingdao" to "青岛",
        "kunming" to "昆明",
        "guiyang" to "贵阳",
        "nanning" to "南宁",
        "taiyuan" to "太原",
        "zhongwu" to "中午",
        "jintian" to "今天",
        "zuotian" to "昨天",
        "shengri" to "生日",
        "chunjie" to "春节",
        "waigong" to "外公",
        "pengyou" to "朋友",
        "tongxue" to "同学",
        "zhangfu" to "丈夫",
        "shuiguo" to "水果",
        "mianbao" to "面包",
        "yinliao" to "饮料",
        "caihong" to "彩虹",
        "gaoxing" to "高兴",
        "shengqi" to "生气",
        "taiyang" to "太阳",
        "dianche" to "电车",
        "gongzuo" to "工作",
        "chengji" to "成绩",
        "woaini" to "我爱你",
        "xiexie" to "谢谢",
        "bukeqi" to "不客气",
        "weixin" to "微信",
        "shouji" to "手机",
        "xitong" to "系统",
        "dalian" to "大连",
        "xiamen" to "厦门",
        "suzhou" to "苏州",
        "ningbo" to "宁波",
        "fuzhou" to "福州",
        "haikou" to "海口",
        "xining" to "西宁",
        "urumqi" to "乌鲁木齐",
        "harbin" to "哈尔滨",
        "xingqi" to "星期",
        "jiejie" to "姐姐",
        "meimei" to "妹妹",
        "nainai" to "奶奶",
        "shushu" to "叔叔",
        "laoshi" to "老师",
        "shucai" to "蔬菜",
        "mantou" to "馒头",
        "niunai" to "牛奶",
        "kuaile" to "快乐",
        "xihuan" to "喜欢",
        "rongyi" to "容易",
        "kunnan" to "困难",
        "tianqi" to "天气",
        "senlin" to "森林",
        "huoche" to "火车",
        "kaoshi" to "考试",
        "fenshu" to "分数",
        "nihao" to "你好",
        "wuhan" to "武汉",
        "jinan" to "济南",
        "sanya" to "三亚",
        "xiawu" to "下午",
        "jieri" to "节日",
        "waipo" to "外婆",
        "baozi" to "包子",
        "kafei" to "咖啡",
        "zhang" to "张",
        "huang" to "黄",
        "cheng" to "橙",
        "yanse" to "颜色",
        "jidan" to "简单",
        "fuzha" to "复杂",
        "qiang" to "强",
        "chong" to "虫",
        "qiche" to "汽车",
        "feiji" to "飞机",
        "chuan" to "船",
        "ditie" to "地铁",
        "lunzi" to "轮子",
        "xuexi" to "学习",
        "benzi" to "本子",
        "zhong" to "中",
        "xiong" to "兄",
        "xian" to "咸",
        "wuxi" to "无锡",
        "lasa" to "拉萨",
        "nian" to "年",
        "miao" to "秒",
        "baba" to "爸爸",
        "mama" to "妈妈",
        "gege" to "哥哥",
        "didi" to "弟弟",
        "yeye" to "爷爷",
        "qizi" to "妻子",
        "yang" to "羊",
        "shui" to "睡",
        "tian" to "甜",
        "suan" to "酸",
        "qian" to "千",
        "ling" to "零",
        "tiao" to "条",
        "jian" to "件",
        "hong" to "红",
        "zong" to "棕",
        "chou" to "丑",
        "huai" to "坏",
        "xiao" to "小",
        "pang" to "胖",
        "shou" to "瘦",
        "kuai" to "快",
        "qing" to "青",
        "feng" to "风",
        "dian" to "电",
        "shan" to "山",
        "niao" to "鸟",
        "zhan" to "站",
        "ting" to "庭",
        "shuo" to "说",
        "gong" to "工",
        "tong" to "童",
        "hao" to "好",
        "shi" to "十",
        "zai" to "在",
        "you" to "游",
        "yue" to "月",
        "fen" to "粉",
        "ayi" to "阿姨",
        "fan" to "饭",
        "cai" to "彩",
        "rou" to "肉",
        "niu" to "牛",
        "zhu" to "猪",
        "cha" to "茶",
        "jiu" to "旧",
        "san" to "三",
        "liu" to "六",
        "bai" to "白",
        "wan" to "玩",
        "ben" to "本",
        "zhi" to "纸",
        "lan" to "蓝",
        "hei" to "黑",
        "hui" to "灰",
        "jin" to "金",
        "yin" to "阴",
        "hen" to "恨",
        "nan" to "男",
        "mei" to "妹",
        "xin" to "新",
        "gao" to "高",
        "ruo" to "弱",
        "man" to "慢",
        "xue" to "学",
        "lei" to "雷",
        "yun" to "云",
        "hai" to "孩",
        "cao" to "草",
        "hua" to "画",
        "shu" to "书",
        "gou" to "狗",
        "mao" to "猫",
        "che" to "车",
        "lun" to "轮",
        "ban" to "班",
        "dao" to "到",
        "lai" to "来",
        "zou" to "走",
        "pao" to "跑",
        "fei" to "飞",
        "chi" to "吃",
        "zuo" to "坐",
        "kan" to "看",
        "xie" to "写",
        "ren" to "人",
        "lao" to "老",
        "jia" to "家",
        "jie" to "姐",
        "sun" to "孙",
        "wo" to "我",
        "ai" to "矮",
        "ni" to "你",
        "ma" to "吗",
        "de" to "的",
        "le" to "了",
        "qq" to "QQ",
        "ri" to "日",
        "yu" to "雨",
        "ji" to "鸡",
        "la" to "辣",
        "yi" to "一",
        "er" to "儿",
        "si" to "四",
        "wu" to "五",
        "qi" to "起",
        "ba" to "八",
        "di" to "弟",
        "ge" to "个",
        "ke" to "课",
        "lv" to "绿",
        "zi" to "子",
        "se" to "色",
        "da" to "大",
        "he" to "喝",
        "hu" to "湖",
        "bi" to "笔",
        "bu" to "不",
        "qu" to "去",
        "du" to "读",
        "xi" to "习",
        "nv" to "女",
        "fu" to "父",
        "mu" to "母",
        "a1" to "ā",
        "a2" to "á",
        "a3" to "ǎ",
        "a4" to "à",
        "e1" to "ē",
        "e2" to "é",
        "e3" to "ě",
        "e4" to "è",
        "i1" to "ī",
        "i2" to "í",
        "i3" to "ǐ",
        "i4" to "ì",
        "o1" to "ō",
        "o2" to "ó",
        "o3" to "ǒ",
        "o4" to "ò",
        "u1" to "ū",
        "u2" to "ú",
        "u3" to "ǔ",
        "u4" to "ù",
        "v1" to "ǖ",
        "v2" to "ǘ",
        "v3" to "ǚ",
        "v4" to "ǜ",
    )

    // Tone marks for pinyin
    private val toneMarks = mapOf(
        "a1" to "ā", "a2" to "á", "a3" to "ǎ", "a4" to "à",
        "e1" to "ē", "e2" to "é", "e3" to "ě", "e4" to "è",
        "i1" to "ī", "i2" to "í", "i3" to "ǐ", "i4" to "ì",
        "o1" to "ō", "o2" to "ó", "o3" to "ǒ", "o4" to "ò",
        "u1" to "ū", "u2" to "ú", "u3" to "ǔ", "u4" to "ù",
        "v1" to "ǖ", "v2" to "ǘ", "v3" to "ǚ", "v4" to "ǜ"
    )

    override fun getActions(precedingText: String, toInsert: String): Pair<Int, String> {
        val input = precedingText + toInsert
        
        // Nếu là ký tự Latin, xử lý pinyin
        if (toInsert.matches(Regex("[a-zA-Z]"))) {
            // Tìm pinyin đang gõ từ cuối chuỗi
            val pinyinPattern = Regex("[a-z]+$")
            val match = pinyinPattern.find(input.lowercase())
            
            if (match != null) {
                val currentPinyin = match.value
                
                // Kiểm tra tone marks trước
                for ((pattern, replacement) in toneMarks) {
                    if (currentPinyin.endsWith(pattern)) {
                        // Xóa pinyin cũ và thay bằng tone mark
                        return Pair(currentPinyin.length, replacement)
                    }
                }
                
                // Tìm từ phù hợp nhất với pinyin hiện tại
                var bestMatch: String? = null
                var bestLength = 0
                
                for ((pinyin, chinese) in pinyinToChinese) {
                    // Kiểm tra xem pinyin hiện tại có thể tạo thành từ nào
                    if (currentPinyin.endsWith(pinyin) && pinyin.length > bestLength) {
                        bestMatch = chinese
                        bestLength = pinyin.length
                    }
                }
                
                // Nếu tìm thấy từ phù hợp, thay thế
                if (bestMatch != null && bestLength > 0) {
                    return Pair(bestLength, bestMatch)
                }
                
                // Nếu chưa tìm thấy từ hoàn chỉnh, hiển thị pinyin hiện tại
                return Pair(0, toInsert)
            }
        }
        
        // Nếu không phải ký tự Latin hoặc không có pinyin, reset và trả về ký tự gốc
        return Pair(0, toInsert)
    }
}