package com.example.aikeyboard.text

import com.example.aikeyboard.text.composing.Composer
import android.content.Context
import org.json.JSONObject
import java.io.IOException

class TelexComposer : Composer {
    override val id = "telex"
    override val label = "Telex"
    override val toRead = 2  // Number of characters to read ahead for composition

    private val vowels = setOf('a', 'e', 'i', 'o', 'u', 'y')
    private val consonants = setOf('b', 'c', 'd', 'g', 'h', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'x')
    
    // English words dictionary to avoid Telex conflicts
    private var englishWords: Set<String> = emptySet()
    
    fun loadEnglishWords(context: Context) {
        try {
            val inputStream = context.assets.open("dictionaries/english_words.json")
            val jsonString = inputStream.bufferedReader().use { it.readText() }
            val jsonObject = JSONObject(jsonString)
            val wordsArray = jsonObject.getJSONArray("english_words")
            englishWords = mutableSetOf<String>().apply {
                for (i in 0 until wordsArray.length()) {
                    add(wordsArray.getString(i))
                }
            }
        } catch (e: IOException) {
            // Fallback to empty set if file not found
            englishWords = emptySet()
        }
    }
    
    /**
     * Kiểm tra xem từ hiện tại có phải là tiếng Anh không
     */
    private fun isEnglishWord(text: String): Boolean {
        // Tách từ cuối cùng (sau dấu cách cuối cùng)
        val lastWord = text.split(" ").lastOrNull() ?: return false
        
        // Chỉ kiểm tra từ hoàn chỉnh (3 ký tự trở lên) để tránh làm hỏng Telex
        if (lastWord.length < 3) {
            return false
        }
        
        // Kiểm tra trong từ điển tiếng Anh
        return englishWords.contains(lastWord.lowercase())
    }

    // Telex rules for Vietnamese diacritics
    private val diacriticRules = mapOf(
        "aw" to "ă", "aa" to "â", "dd" to "đ", "ee" to "ê", "oo" to "ô", "ow" to "ơ", "uw" to "ư",
        "uow" to "ươ",
        "af" to "à", "ar" to "ả", "ax" to "ã", "as" to "á", "aj" to "ạ",
        "ăf" to "ằ", "ăr" to "ẳ", "ăx" to "ẵ", "ăs" to "ắ", "ăj" to "ặ",
        "âf" to "ầ", "âr" to "ẩ", "âx" to "ẫ", "âs" to "ấ", "âj" to "ậ",
        "ef" to "è", "er" to "ẻ", "ex" to "ẽ", "es" to "é", "ej" to "ẹ",
        "êf" to "ề", "êr" to "ể", "êx" to "ễ", "ês" to "ế", "êj" to "ệ",
        "if" to "ì", "ir" to "ỉ", "ix" to "ĩ", "is" to "í", "ij" to "ị",
        "of" to "ò", "or" to "ỏ", "ox" to "õ", "os" to "ó", "oj" to "ọ",
        "ôf" to "ồ", "ôr" to "ổ", "ôx" to "ỗ", "ôs" to "ố", "ôj" to "ộ",
        "ơf" to "ờ", "ơr" to "ở", "ơx" to "ỡ", "ơs" to "ớ", "ơj" to "ợ",
        "uf" to "ù", "ur" to "ủ", "ux" to "ũ", "us" to "ú", "uj" to "ụ",
        "ưf" to "ừ", "ưr" to "ử", "ưx" to "ữ", "ưs" to "ứ", "ưj" to "ự",
        "yf" to "ỳ", "yr" to "ỷ", "yx" to "ỹ", "ys" to "ý", "yj" to "ỵ",
        "ăw" to "aw", "âa" to "aa", "đd" to "dd", "êe" to "ee", "ôo" to "oo", "ơw" to "ow", "ưw" to "w", "iêe" to "iee",
        "ươw" to "uow",
        "àf" to "af", "ảr" to "ar", "ãx" to "ax", "ás" to "as", "ạj" to "aj",
        "ằf" to "ăf", "ẳr" to "ăr", "ẵx" to "ăx", "ắs" to "ăs", "ặj" to "ăj",
        "ầf" to "âf", "ẩr" to "âr", "ẫx" to "âx", "ấs" to "âs", "ậj" to "âj",
        "èf" to "ef", "ẻr" to "er", "ẽx" to "ex", "és" to "es", "ẹj" to "ej",
        "ềf" to "êf", "ểr" to "êr", "ễx" to "êx", "ếs" to "ês", "ệj" to "êj",
        "ìf" to "if", "ỉr" to "ir", "ĩx" to "ix", "ís" to "is", "ịj" to "ij",
        "òf" to "of", "ỏr" to "or", "õx" to "ox", "ós" to "os", "ọj" to "oj",
        "ồf" to "ôf", "ổr" to "ôr", "ỗx" to "ôx", "ốs" to "ôs", "ộj" to "ôj",
        "ờf" to "ơf", "ởr" to "ơr", "ỡx" to "ơx", "ớs" to "ơs", "ợj" to "ơj",
        "ùf" to "uf", "ủr" to "ur", "ũx" to "ux", "ús" to "us", "ụj" to "uj",
        "ừf" to "ưf", "ửr" to "ưr", "ữx" to "ưx", "ứs" to "ưs", "ựj" to "ưj",
        "ỳf" to "yf", "ỷr" to "yr", "ỹx" to "yx", "ýs" to "ys", "ỵj" to "yj",
        "àz" to "a", "ảz" to "a", "ãz" to "a", "áz" to "a", "ạz" to "a",
        "ằz" to "ă", "ẳz" to "ă", "ẵz" to "ă", "ắz" to "ă", "ặz" to "ă",
        "ầz" to "â", "ẩz" to "â", "ẫz" to "â", "ấz" to "â", "ậz" to "â",
        "èz" to "e", "ẻz" to "e", "ẽz" to "e", "éz" to "e", "ẹz" to "e",
        "ềz" to "ê", "ểz" to "ê", "ễz" to "ê", "ếz" to "ê", "ệz" to "ê",
        "ìz" to "i", "ỉz" to "i", "ĩz" to "i", "íz" to "i", "ịz" to "i",
        "òz" to "o", "ỏz" to "o", "õz" to "o", "óz" to "o", "ọz" to "o",
        "ồz" to "ô", "ổz" to "ô", "ỗz" to "ô", "ốz" to "ô", "ộz" to "ô",
        "ờz" to "ơ", "ởz" to "ơ", "ỡz" to "ơ", "ớz" to "ơ", "ợz" to "ơ",
        "ùz" to "u", "ủz" to "u", "ũz" to "u", "úz" to "u", "ụz" to "u",
        "ừz" to "ư", "ửz" to "ư", "ữz" to "ư", "ứz" to "ư", "ựz" to "ư",
        "ỳz" to "y", "ỷz" to "y", "ỹz" to "y", "ýz" to "y", "ỵz" to "y",

        "áf" to "à", "ár" to "ả", "áx" to "ã", "áj" to "ạ", 
        "às" to "á", "àr" to "ả", "àx" to "ã", "àj" to "ạ", 
        "ảs" to "á", "ảf" to "à", "ảx" to "ã", "ảj" to "ạ", 
        "ãs" to "á", "ãf" to "à", "ãr" to "ả", "ãj" to "ạ", 
        "ạs" to "á", "ạf" to "à", "ạr" to "ả", "ạx" to "ã", 
        "ấf" to "ầ", "ấr" to "ẩ", "ấx" to "ẫ", "ấj" to "ậ", 
        "ầs" to "ấ", "ầr" to "ẩ", "ầx" to "ẫ", "ầj" to "ậ", 
        "ẩs" to "ấ", "ẩf" to "ầ", "ẩx" to "ẫ", "ẩj" to "ậ", 
        "ẫs" to "ấ", "ẫf" to "ầ", "ẫr" to "ẩ", "ẫj" to "ậ", 
        "ậs" to "ấ", "ậf" to "ầ", "ậr" to "ẩ", "ậx" to "ẫ", 
        "ắf" to "ằ", "ắr" to "ẳ", "ắx" to "ẵ", "ắj" to "ặ", 
        "ằs" to "ắ", "ằr" to "ẳ", "ằx" to "ẵ", "ằj" to "ặ", 
        "ẳs" to "ắ", "ẳf" to "ằ", "ẳx" to "ẵ", "ẳj" to "ặ", 
        "ẵs" to "ắ", "ẵf" to "ằ", "ẵr" to "ẳ", "ẵj" to "ặ", 
        "ặs" to "ắ", "ặf" to "ằ", "ặr" to "ẳ", "ặx" to "ẵ",
        "éf" to "è", "ér" to "ẻ", "éx" to "ẽ", "éj" to "ẹ", 
        "ès" to "é", "èr" to "ẻ", "èx" to "ẽ", "èj" to "ẹ", 
        "ẻs" to "é", "ẻf" to "è", "ẻx" to "ẽ", "ẻj" to "ẹ", 
        "ẽs" to "é", "ẽf" to "è", "ẽr" to "ẻ", "ẽj" to "ẹ", 
        "ẹs" to "é", "ẹf" to "è", "ẹr" to "ẻ", "ẹx" to "ẽ",
        "ếf" to "ề", "ếr" to "ể", "ếx" to "ễ", "ếj" to "ệ", 
        "ềs" to "ế", "ềr" to "ể", "ềx" to "ễ", "ềj" to "ệ", 
        "ểs" to "ế", "ểf" to "ề", "ểx" to "ễ", "ểj" to "ệ", 
        "ễs" to "ế", "ễf" to "ề", "ễr" to "ể", "ễj" to "ệ", 
        "ệs" to "ế", "ệf" to "ề", "ệr" to "ể", "ệx" to "ễ",
        "íf" to "ì", "ír" to "ỉ", "íx" to "ĩ", "íj" to "ị", 
        "ìs" to "í", "ìr" to "ỉ", "ìx" to "ĩ", "ìj" to "ị", 
        "ỉs" to "í", "ỉf" to "ì", "ỉx" to "ĩ", "ỉj" to "ị", 
        "ĩs" to "í", "ĩf" to "ì", "ĩr" to "ỉ", "ĩj" to "ị", 
        "ịs" to "í", "ịf" to "ì", "ịr" to "ỉ", "ịx" to "ĩ", 
        "óf" to "ò", "ór" to "ỏ", "óx" to "õ", "ój" to "ọ", 
        "òs" to "ó", "òr" to "ỏ", "òx" to "õ", "òj" to "ọ", 
        "ỏs" to "ó", "ỏf" to "ò", "ỏx" to "õ", "ỏj" to "ọ", 
        "õs" to "ó", "õf" to "ò", "õr" to "ỏ", "õj" to "ọ", 
        "ọs" to "ó", "ọf" to "ò", "ọr" to "ỏ", "ọx" to "õ", 
        "ốf" to "ồ", "ốr" to "ổ", "ốx" to "ỗ", "ốj" to "ộ", 
        "ồs" to "ố", "ồr" to "ổ", "ồx" to "ỗ", "ồj" to "ộ", 
        "ổs" to "ố", "ổf" to "ồ", "ổx" to "ỗ", "ổj" to "ộ", 
        "ỗs" to "ố", "ỗf" to "ồ", "ỗr" to "ổ", "ỗj" to "ộ", 
        "ộs" to "ố", "ộf" to "ồ", "ộr" to "ổ", "ộx" to "ỗ", 
        "ớf" to "ờ", "ớr" to "ở", "ớx" to "ỡ", "ớj" to "ợ", 
        "ờs" to "ớ", "ờr" to "ở", "ờx" to "ỡ", "ờj" to "ợ", 
        "ởs" to "ớ", "ởf" to "ờ", "ởx" to "ỡ", "ởj" to "ợ", 
        "ỡs" to "ớ", "ỡf" to "ờ", "ỡr" to "ở", "ỡj" to "ợ", 
        "ợs" to "ớ", "ợf" to "ờ", "ợr" to "ở", "ợx" to "ỡ", 
        "úf" to "ù", "úr" to "ủ", "úx" to "ũ", "új" to "ụ", 
        "ùs" to "ú", "ùr" to "ủ", "ùx" to "ũ", "ùj" to "ụ", 
        "ủs" to "ú", "ủf" to "ù", "ủx" to "ũ", "ủj" to "ụ", 
        "ũs" to "ú", "ũf" to "ù", "ũr" to "ủ", "ũj" to "ụ", 
        "ụs" to "ú", "ụf" to "ù", "ụr" to "ủ", "ụx" to "ũ", 
        "ứf" to "ừ", "ứr" to "ử", "ứx" to "ữ", "ứj" to "ự", 
        "ừs" to "ứ", "ừr" to "ử", "ừx" to "ữ", "ừj" to "ự", 
        "ửs" to "ứ", "ửf" to "ừ", "ửx" to "ữ", "ửj" to "ự", 
        "ữs" to "ứ", "ữf" to "ừ", "ữr" to "ử", "ữj" to "ự", 
        "ựs" to "ứ", "ựf" to "ừ", "ựr" to "ử", "ựx" to "ữ", 
        "ýf" to "ỳ", "ýr" to "ỷ", "ýx" to "ỹ", "ýj" to "ỵ", 
        "ỳs" to "ý", "ỳr" to "ỷ", "ỳx" to "ỹ", "ỳj" to "ỵ", 
        "ỷs" to "ý", "ỷf" to "ỳ", "ỷx" to "ỹ", "ỷj" to "ỵ", 
        "ỹs" to "ý", "ỹf" to "ỳ", "ỹr" to "ỷ", "ỹj" to "ỵ", 
        "ỵs" to "ý", "ỵf" to "ỳ", "ỵr" to "ỷ", "ỵx" to "ỹ", 

        "gias" to "giá", "giaf" to "già", "giar" to "giả", "giax" to "giã", "giaj" to "giạ",
        "gía" to "giá", "gìa" to "già", "gỉa" to "giả", "gĩa" to "giã", "gịa" to "giạ",
        "gíă" to "giắ", "gìă" to "giằ", "gỉă" to "giẳ", "gĩă" to "giẵ", "gịă" to "giặ",
        "gíâ" to "giấ", "gìâ" to "giầ", "gỉâ" to "giẩ", "gĩâ" to "giẫ", "gịâ" to "giậ",        
        "gíe" to "gié", "gìe" to "giè", "gỉe" to "giẻ", "gĩe" to "giẽ", "gịe" to "giẹ",
        "gíê" to "giế", "gìê" to "giề", "gỉê" to "giể", "gĩê" to "giễ", "gịê" to "giệ",
        "gío" to "gió", "gìo" to "giò", "gỉo" to "giỏ", "gĩo" to "giõ", "gịo" to "giọ",
        "gíô" to "giố", "gìô" to "giồ", "gỉô" to "giổ", "gĩô" to "giỗ", "gịô" to "giộ",
        "gíơ" to "giớ", "gìơ" to "giờ", "gỉơ" to "giở", "gĩơ" to "giỡ", "gịơ" to "giợ",
        "gius" to "giú", "giuf" to "giù", "giur" to "giủ", "giux" to "giũ", "giuj" to "giụ",
        "gíu" to "giú", "gìu" to "giù", "gỉu" to "giủ", "gĩu" to "giũ", "gịu" to "giụ",
        "gíư" to "giứ", "gìư" to "giừ", "gỉư" to "giử", "gĩư" to "giữ", "gịư" to "giự",

        "ghíê" to "ghiế", "ghìê" to "ghiề", "ghỉê" to "ghiể", "ghĩê" to "ghiễ", "ghịê" to "ghiệ",


        "acw" to "ăc", "amw" to "ăm", "anw" to "ăn", "apw" to "ăp", "atw" to "ăt", "angw" to "ăng",
        "aca" to "âc", "ama" to "âm", "ana" to "ân", "apa" to "âp", "ata" to "ât", "aua" to "âu", "aya" to "ây", "anga" to "âng",
        "eme" to "êm", "ene" to "ên", "epe" to "êp", "ete" to "êt", "enhe" to "ênh",
        "oio" to "ôi","omo" to "ôm", "ono" to "ôn", "opo" to "ôp", "oto" to "ôt", "ongo" to "ông",
        "oiw" to "ơi", "omw" to "ơm", "onw" to "ơn", "opw" to "ơp", "otw" to "ơt",
        "uaw" to "ưa", "ucw" to "ưc", "uiw" to "ưi", "umw" to "ưm", "unw" to "ưn", "utw" to "ưt", "uuw" to "ưu", "ungw" to "ưng",
        "ieme" to "iêm", "iene" to "iên", "iepe" to "iêp", "iete" to "iêt", "ieue" to "iêu", "ienge" to "iêng", 
        "uocw" to "ươc", "uoiw" to "ươi", "uomw" to "ươm", "uonw" to "ươn", "uotw" to "ươt", "uongw" to "ương",
        "uoco" to "uôc", "uoio" to "uôi", "uomo" to "uôm", "uono" to "uôn", "uoto" to "uôt", "uongo" to "uông",
        "uyene" to "uyên", "uyete" to "uyêt",
        "yeme" to "yêm", "yene" to "yên", "yete" to "yêt", "yeue" to "yêu", "yenge" to "yêng",
        
        "ăca" to "âc", "ăma" to "âm", "ăna" to "ân", "ăpa" to "âp", "ăta" to "ât", "ănga" to "âng",
        "âcw" to "ăc", "âmw" to "ăm", "ânw" to "ăn", "âpw" to "ăp", "âtw" to "ăt", "ângw" to "ăng",
        "ôiw" to "ơi", "ômw" to "ơm", "ônw" to "ơn", "ôpw" to "ơp", "ôtw" to "ơt",
        "ơio" to "ôi", "ơmo" to "ôm", "ơno" to "ôn", "ơpo" to "ôp", "ơto" to "ôt",

        "ăcw" to "acw", "ămw" to "amw", "ănw" to "anw", "ăpw" to "apw", "ătw" to "atw", "ăngw" to "angw",
        "âca" to "aca", "âma" to "ama", "âna" to "ana", "âpa" to "apa", "âta" to "ata", "âua" to "aua", "âya" to "aya", "ânga" to "anga",
        "ême" to "eme", "êne" to "ene", "êpe" to "epe", "ête" to "ete",
        "ôio" to "oio", "ômo" to "omo", "ôno" to "ono", "ôpo" to "opo", "ôto" to "oto", "ôngo" to "ongo",
        "ơmw" to "omw", "ơnw" to "onw", "ơpw" to "opw", "ơtw" to "otw",
        "ưaw" to "uaw", "ưcw" to "ucw", "ưiw" to "uiw", "ưmw" to "umw", "ưnw" to "unw" , "ưtw" to "utw", "ưuw" to "uuw", "ưngw" to "ungw",
        "iême" to "ieme", "iêne" to "iene", "iêpe" to "iepe", "iête" to "iete", "iêue" to "ieue", "iênge" to "ienge",
        "ươcw" to "uocw", "ươiw" to "uoiw", "ươmw" to "uomw", "ươnw" to "uonw", "ươtw" to "uotw", "ươngw" to "uongw",
        "uyêne" to "uyene", "uyêt" to "uyete",
        "yême" to "yeme", "yêne" to "yene", "yête" to "yete", "yêue" to "yeue", "yênge" to "yenge",
        
        "acs" to "ác", "acj" to "ạc",
        "achs" to "ách", "achj" to "ạch",
        "ais" to "ái", "aif" to "ài", "air" to "ải", "aix" to "ãi", "aij" to "ại",
        "ams" to "ám", "amf" to "àm", "amr" to "ảm", "amx" to "ãm", "amj" to "ạm",
        "ans" to "án" , "anf" to "àn", "anr" to "ản", "anx" to "ãn", "anj" to "ạn",
        "aos" to "áo", "aof" to "ào", "aor" to "ảo", "aox" to "ão", "aoj" to "ạo",
        "aps" to "áp", "apj" to "ạp",
        "ats" to "át", "atj" to "ạt",
        "aus" to "áu", "auf" to "àu", "aur" to "ảu", "aux" to "ãu", "auj" to "ạu",
        "ays" to "áy", "ayf" to "ày", "ayr" to "ảy", "ayx" to "ãy", "ayj" to "ạy",
        "angs" to "áng", "angf" to "àng", "angr" to "ảng", "angx" to "ãng", "angj" to "ạng",
        "anhs" to "ánh", "anhf" to "ành", "anhr" to "ảnh", "anhx" to "ãnh", "anhj" to "ạnh",
        
        "ács" to "acs", "ạcj" to "acj",
        "áchs" to "achs", "ạchj" to "achj",
        "áis" to "ais", "àif" to "aif", "ảir" to "air", "ãix" to "aix", "ạij" to "aij",
        "áms" to "ams", "àmf" to "amf", "ảmr" to "amr", "ãmx" to "amx", "ạmj" to "amj",
        "áns" to "ans", "ànf" to "anf", "ảnr" to "anr", "ãnx" to "anx", "ạnj" to "anj",
        "áos" to "aos", "àof" to "aof", "ảor" to "aor", "ãox" to "aox", "ạoj" to "aoj",
        "áps" to "aps", "ạpj" to "apj",
        "áts" to "ats", "ạtj" to "atj",
        "áus" to "aus", "àuf" to "auf", "ảur" to "aur", "ãux" to "aux", "ạuj" to "auj",
        "áys" to "ays", "àyf" to "ayf", "ảyr" to "ayr", "ãyx" to "ayx", "ạyj" to "ayj",
        "ángs" to "angs", "àngf" to "angf", "ảngr" to "angr", "ãngx" to "angx", "ạngj" to "angj",
        "ánhs" to "anhs", "ànhf" to "anhf", "ảnhr" to "anhr", "ãnhx" to "anhx", "ạnhj" to "anhj",
        
        "ecs" to "éc", "ecj" to "ẹc",
        "ems" to "ém", "emf" to "èm", "emr" to "ẻm", "emx" to "ẽm", "emj" to "ẹm", 
        "ens" to "én", "enf" to "èn", "enr" to "ẻn", "enx" to "ẽn", "enj" to "ẹn",
        "eps" to "ép", "epj" to "ẹp",
        "ets" to "ét", "etj" to "ẹt",
        "engs" to "éng", "engf" to "èng", "engr" to "ẻng", "engx" to "ẽng", "engj" to "ẹng",
        "enhs" to "énh", "enhf" to "ènh", "enhr" to "ẻnh", "enhx" to "ẽnh", "enhj" to "ẹnh",

        "écs" to "ecs", "ẹcj" to "ecj",
        "éms" to "ems", "èmf" to "emf", "ẻmr" to "emr", "ẽmx" to "emx", "ẹmj" to "emj", 
        "éns" to "ens", "ènf" to "enf","ẻnr" to "enr", "ẽnx" to "enx", "ẹnj" to "enj",
        "éps" to "eps", "ẹpj" to "epj",
        "éts" to "ets", "ẹtj" to "etj",
        "éngs" to "engs", "èngf" to "engf", "ẻngr" to "engr", "ẽngx" to "engx", "ẹngj" to "engj",
        "énhs" to "enhs", "ènhf" to "enhf", "ẻnhr" to "enhr", "ẽnh" to "enhx", "ẹnh" to "enhj",

        "ias" to "ía", "iaf" to "ìa", "iar" to "ỉa", "iax" to "ĩa", "iaj" to "ịa",
        "ics" to "íc", "icj" to "ịc",      
        "ims" to "ím", "imf" to "ìm", "imr" to "ỉm", "imx" to "ĩm", "imj" to "ịm",
        "ins" to "ín", "inf" to "ìn", "inr" to "ỉn", "inx" to "ĩn", "inj" to "ịn",
        "ips" to "íp", "ipj" to "ịp",
        "its" to "ít", "itj" to "ịt",
        "ius" to "íu", "iuf" to "ìu", "iur" to "ỉu", "iux" to "ĩu", "iuj" to "ịu",
        "ichs" to "ích", "ichj" to "ịch",
        "inhs" to "ính", "inhf" to "ình", "inhr" to "ỉnh", "inhx" to "ĩnh", "inhj" to "ịnh",

        "ías" to "ias", "ìaf" to "iaf", "ỉar" to "iar", "ĩax" to "iax", "ịaj" to "iaj",
        "iás" to "ias", "iàf" to "iaf", "iảr" to "iar", "iãx" to "iax", "iạj" to "iaj",
        "ícs" to "ics", "ịcj" to "icj",
        "íms" to "ims", "ìmf" to "imf", "ỉmr" to "imr", "ĩmx" to "imx", "ịmj" to "imj",
        "íns" to "ins", "ìnf" to "inf", "ỉnr" to "inr", "ĩnx" to "inx", "ịnj" to "inj",
        "íps" to "ips", "ịpj" to "ipj",
        "íts" to "its", "ịtj" to "itj",
        "íus" to "ius", "ìuf" to "iuf", "ỉur" to "iur", "ĩux" to "iux", "ịuj" to "iuj",
        "íchs" to "ichs", "ịchj" to "ichj",
        "ínhs" to "inhs", "ìnhf" to "inhf", "ỉnhr" to "inhr", "ĩnhx" to "inhx", "ịnhj" to "inhj",

        "oas" to "óa", "oaf" to "òa", "oar" to "ỏa", "oax" to "õa", "oaj" to "ọa",
        "ocs" to "óc", "ocj" to "ọc",
        "ois" to "ói", "oif" to "òi", "oir" to "ỏi", "oix" to "õi", "oij" to "ọi",
        "oms" to "óm", "omf" to "òm", "omr" to "ỏm", "omx" to "õm", "omj" to "ọm",
        "ons" to "ón", "onf" to "òn", "onr" to "ỏn", "onx" to "õn", "onj" to "ọn",
        "ops" to "óp", "opj" to "ọp",
        "ots" to "ót", "otj" to "ọt",
        "ongs" to "óng", "ongf" to "òng", "ongr" to "ỏng", "ongx" to "õng", "ongj" to "ọng",

        "óas" to "oas", "òaf" to "oaf", "ỏar" to "oar", "õax" to "oax", "ọaj" to "oaj",
        "ócs" to "ocs", "ọcj" to "ocj",
        "óis" to "ois", "òif" to "oif", "ỏir" to "oir", "õix" to "oix", "ọij" to "oij",
        "óms" to "oms", "òmf" to "omf", "ỏmr" to "omr", "õmx" to "omx", "ọmj" to "omj",
        "óns" to "ons", "ònf" to "onf", "ỏnr" to "onr", "õnx" to "onx", "ọnj" to "onj",
        "óps" to "ops", "ọpj" to "opj",
        "óts" to "ots", "ọtj" to "otj",
        "óngs" to "ongs", "òngf" to "ongf", "ỏngr" to "ongr", "õngx" to "ongx", "ọngj" to "ongj",

        "uas" to "úa", "uaf" to "ùa", "uar" to "ủa", "uax" to "ũa", "uaj" to "ụa",
        "ucs" to "úc", "ucj" to "ục",
        "uis" to "úi", "uif" to "ùi", "uir" to "ủi", "uix" to "ũi", "uij" to "ụi",
        "ums" to "úm", "umf" to "ùm", "umr" to "ủm", "umx" to "ũm", "umj" to "ụm",     
        "uns" to "ún", "unf" to "ùn", "unr" to "ủn", "unx" to "ũn", "unj" to "ụn",
        "ups" to "úp", "upj" to "ụp",
        "uts" to "út", "utj" to "ụt",
        "uus" to "úu", "uuf" to "ùu", "uur" to "ủu", "uux" to "ũu", "uuj" to "ụu",
        "uys" to "úy", "uyf" to "ùy", "uyr" to "ủy", "uyx" to "ũy", "uyj" to "ụy",
        "ungs" to "úng", "ungf" to "ùng", "ungr" to "ủng", "ungx" to "ũng", "ungj" to "ụng",

        "úas" to "uas", "ùaf" to "uaf", "ủar" to "uar", "ũax" to "uax", "ụaj" to "uaj",
        "úcs" to "ucs", "ụcj" to "ucj",
        "úis" to "uis", "ùif" to "uif", "ủir" to "uir", "ũix" to "uix", "ụij" to "uij",
        "úms" to "ums", "ùmf" to "umf", "ủmr" to "umr", "ũmx" to "umx", "ụmj" to "umj",
        "úns" to "uns", "ùnf" to "unf", "ủnr" to "unr", "ũnx" to "unx", "ụnj" to "unj",
        "úps" to "ups", "ụpj" to "upj",
        "úts" to "uts", "ụtj" to "utj",
        "úus" to "uus", "ùuf" to "uuf", "ủur" to "uur", "ũux" to "uux", "ụuj" to "uuj",
        "úu " to "uus", "ùu " to "uuf", "ủu " to "uur", "ũu " to "uux", "ụu " to "uuj",
        "úys" to "uys", "ùyf" to "uyf", "ủyr" to "uyr", "ũyx" to "uyx", "ụyj" to "uyj",
        "úngs" to "ungs", "ùngf" to "ungf", "ủngr" to "ungr", "ũngx" to "ungx", "ụngj" to "ungj",

        "ăcs" to "ắc", "ăcj" to "ặc",
        "ácw" to "ắc", "ạcw" to "ặc",
        "ăms" to "ắm", "ămf" to "ằm", "ămr" to "ẳm", "ămx" to "ẵm", "ămj" to "ặm",
        "ámw" to "ắm", "àmw" to "ằm", "ảmw" to "ẳm", "ãmw" to "ẵm", "ạmw" to "ặm",
        "ăns" to "ắn", "ănf" to "ằn", "ănr" to "ẳn", "ănx" to "ẵn", "ănj" to "ặn",
        "ánw" to "ắn", "ànw" to "ằn", "ảnw" to "ẳn", "ãnw" to "ẵn", "ạnw" to "ặn",
        "ăps" to "ắp", "ăpj" to "ặp",
        "ápw" to "ắp", "ạpw" to "ặp",
        "ăts" to "ắt", "ătj" to "ặt",
        "átw" to "ắt", "ạtw" to "ặt",
        "ăngs" to "ắng", "ăngf" to "ằng", "ăngr" to "ẳng", "ăngx" to "ẵng", "ăngj" to "ặng",
        "ángw" to "ắng", "àngw" to "ằng", "ảngw" to "ẳng", "ãngw" to "ẵng", "ạngw" to "ặng",

        "ắcw" to "ácw", "ắcs" to "ăcs", "ăcsw" to "acsw", "ácws" to "acws", 
        "ặcw" to "ạcw", "ặcj" to "ăcj", "ăcjw" to "acjw", "ạcwj" to "acwj", 
        "ắms" to "ăms", "ắmw" to "ámw", "ămsw" to "amsw", "ámws" to "amws", 
        "ằmf" to "ămf", "ằmw" to "àmw", "ămfw" to "amfw", "àmwf" to "amwf",
        "ẳmr" to "ămr", "ẳmw" to "ảmw", "ămrw" to "amrw", "ảmwr" to "amwr",
        "ẵmx" to "ămx", "ẵmw" to "ãmw", "ămxw" to "amxw", "ãmwx" to "amwx", 
        "ặmj" to "ămj", "ặmw" to "ạmw", "ămjw" to "amjw", "ạmwj" to "amwj",
        "ắns" to "ăns", "ắnw" to "ánw", "ănsw" to "answ", "ánws" to "anws",
        "ằnf" to "ănf", "ằnw" to "ànw", "ănfw" to "anfw", "ànwf" to "anwf", 
        "ẳnr" to "ănr", "ẳnw" to "ảnw", "ănrw" to "anrw", "ảnwr" to "anwr",
        "ẵnx" to "ănx", "ẵnw" to "ãnw", "ănxw" to "anxw", "ãnwx" to "anwx",
        "ặnj" to "ănj", "ặnw" to "ạnw", "ănjw" to "anjw", "ạnwj" to "anwj",
        "ắps" to "ăps", "ắpw" to "ápw", "ăpsw" to "apsw", "ápws" to "apws",
        "ặpj" to "ăpj", "ặpw" to "ạpw", "ăpjw" to "apjw", "ạpwj" to "apwj",
        "ắts" to "ăts", "ắtw" to "átw", "ătsw" to "atws", "átws" to "atws",
        "ặtj" to "ătj", "ặtw" to "ạtw", "ătjw" to "atjw", "ạtwj" to "atwj",
        "ắngs" to "ăngs", "ắngw" to "ángw", "ăngsw" to "angsw", "ángws" to "angws",
        "ằngf" to "ăngf", "ằngw" to "àngw", "ăngfw" to "angfw", "àngwf" to "angwf",
        "ẳngr" to "ăngr", "ẳngw" to "ảngw", "ăngrw" to "angrw", "ảngwr" to "angwr",
        "ẵngx" to "ăngx", "ẵngw" to "ãngw", "ăngxw" to "angxw", "ãngwx" to "angwx",
        "ặngj" to "ăngj", "ặngw" to "ạngw", "ăngjw" to "angjw", "ạngwj" to "angwj",

        "âcs" to "ấc", "âcj" to "ậc",
        "áca" to "ấc", "ạca" to "ậc",
        "âms" to "ấm", "âmf" to "ầm", "âmr" to "ẩm", "âmx" to "ẫm", "âmj" to "ậm",
        "áma" to "ấm", "àma" to "ầm", "ảma" to "ẩm", "ãma" to "ẫm", "ạma" to "ậm",
        "âns" to "ấn", "ânf" to "ần", "ânr" to "ẩn", "ânx" to "ẫn", "ânj" to "ận",
        "ána" to "ấn", "àna" to "ần", "ảna" to "ẩn", "ãna" to "ẫn", "ạna" to "ận",
        "âps" to "ấp", "âpj" to "ập",
        "ápa" to "ấp", "ạpa" to "ập",
        "âts" to "ất", "âtj" to "ật",
        "áta" to "ất", "ạta" to "ật",
        "âus" to "ấu", "âuf" to "ầu", "âur" to "ẩu", "âux" to "ẫu", "âuj" to "ậu",
        "áua" to "ấu", "àua" to "ầu", "ảua" to "ẩu", "ãua" to "ẫu", "ạua" to "ậu",
        "âys" to "ấy", "âyf" to "ầy", "âyr" to "ẩy", "âyx" to "ẫy", "âyj" to "ậy",
        "áya" to "ấy", "àya" to "ầy", "ảya" to "ẩy", "ãya" to "ẫy", "ạya" to "ậy",
        "ângs" to "ấng", "ângf" to "ầng", "ângr" to "ẩng", "ângx" to "ẫng", "ângj" to "ậng",
        "ánga" to "ấng", "ànga" to "ầng", "ảnga" to "ẩng", "ãnga" to "ẫng", "ạnga" to "ậng",

        "ấcs" to "âcs", "ấca" to "áca", "âcsa" to "acsa", "ácas" to "acas",
        "ậcj" to "âcj", "ậca" to "ạca", "âcja" to "acja", "ạcaj" to "acaj",
        "ấms" to "âms", "ấma" to "áma", "âmsa" to "amsa", "ámas" to "amas", 
        "ầmf" to "âmf", "ầma" to "àma", "âmfa" to "amfa", "àmaf" to "amaf",
        "ẩmr" to "âmr", "ẩma" to "ảma", "âmra" to "amra", "ảmar" to "amar",
        "ẫmx" to "âmx", "ẫma" to "ãma", "âmxa" to "amxa", "ãmax" to "amax", 
        "ậmj" to "âmj", "ậma" to "ạma", "âmja" to "amja", "ạmaj" to "amaj",
        "ấns" to "âns", "ấna" to "ána", "ânsa" to "ansa", "ánas" to "anas",
        "ầnf" to "ânf", "ầna" to "àna", "ânfa" to "anfa", "ànaf" to "anaf", 
        "ẩnr" to "ânr", "ẩna" to "ảna", "ânra" to "anra", "ảnar" to "anar",
        "ẫnx" to "ânx", "ẫna" to "ãna", "ânxa" to "anxa", "ãnax" to "anax",
        "ậnj" to "ânj", "ậna" to "ạna", "ânja" to "anja", "ạnaj" to "anaj",
        "ấps" to "âps", "ấpa" to "ápa", "âpsa" to "apsa", "ápas" to "apas",
        "ậpj" to "âpj", "ậpa" to "ạpa", "âpja" to "apja", "ạpaj" to "apaj",
        "ấts" to "âts", "ấta" to "áta", "âtsa" to "atas", "átas" to "atas",
        "ậtj" to "âtj", "ậta" to "ạta", "âtja" to "atja", "ạtaj" to "ataj",
        "ấus" to "âus", "ấua" to "áua", "âusa" to "ausa", "áuas" to "auas", 
        "ầuf" to "âuf", "ầua" to "àua", "âufa" to "aufa", "àuaf" to "auaf",
        "ẩur" to "âur", "ẩua" to "ảua", "âura" to "aura", "ảuar" to "auar",
        "ẫux" to "âux", "ẫua" to "ãua", "âuxa" to "auxa", "ãuax" to "auax", 
        "ậuj" to "âuj", "ậua" to "ạua", "âuja" to "auja", "ạuaj" to "auaj",
        "ấys" to "âys", "ấya" to "áya", "âysa" to "aysa", "áyas" to "ayas", 
        "ầyf" to "âyf", "ầya" to "àya", "âyfa" to "ayfa", "àyaf" to "ayaf",
        "ẩyr" to "âyr", "ẩya" to "ảya", "âyra" to "ayra", "ảyar" to "ayar",
        "ẫyx" to "âyx", "ẫya" to "ãya", "âyxa" to "ayxa", "ãyax" to "ayax", 
        "ậyj" to "âyj", "ậya" to "ạya", "âyja" to "ayja", "ạyaj" to "ayaj",
        "ấngs" to "ângs", "ấnga" to "ánga", "ângsa" to "angsa", "ángas" to "angas", 
        "ầngf" to "ângf", "ầnga" to "ànga", "ângfa" to "angfa", "àngaf" to "angaf",
        "ẩngr" to "ângr", "ẩnga" to "ảnga", "ângra" to "angra", "ảngar" to "angar",
        "ẫngx" to "ângx", "ẫnga" to "ãnga", "ângxa" to "angxa", "ãngax" to "angax", 
        "ậngj" to "ângj", "ậnga" to "ạnga", "ângja" to "angja", "ạngaj" to "angaj",

        "êcs" to "ếc", "êcj" to "ệc",
        "éce" to "ếc", "ẹce" to "ệc",
        "êms" to "ếm", "êmf" to "ềm", "êmr" to "ểm", "êmx" to "ễm", "êmj" to "ệm",
        "éme" to "ếm", "ème" to "ềm", "ẻme" to "ểm", "ẽme" to "ễm", "ẹme" to "ệm",
        "êns" to "ến", "ênf" to "ền", "ênr" to "ển", "ênx" to "ễn", "ênj" to "ện",
        "éne" to "ến", "ène" to "ền", "ẻne" to "ển", "ẽne" to "ễn", "ẹne" to "ện",
        "êps" to "ếp", "êpj" to "ệp",
        "épe" to "ếp", "ẹpe" to "ệp",
        "êts" to "ết", "êtj" to "ệt",
        "éte" to "ết", "ẹte" to "ệt",
        "êchs" to "ếch", "êchj" to "ệch",
        "echs" to "éch", "echj" to "ẹch",
        "éche" to "ếch", "ẹche" to "ệch",
        "ênhs" to "ếnh", "ênhf" to "ềnh", "ênhr" to "ểnh", "ênhx" to "ễnh", "ênhj" to "ệnh",
        "énhe" to "ếnh", "ènhe" to "ềnh", "ẻnhe" to "ểnh", "ẽnhe" to "ễnh", "ẹnhe" to "ệnh",

        "ếms" to "êms", "ếme" to "éme", "êmse" to "emse", "émes" to "emes",
        "ềmf" to "êmf", "ềme" to "ème", "êmfe" to "emfe", "èmef" to "emef",
        "ểmr" to "êmr", "ểme" to "ẻme", "êmre" to "emre", "ẻmer" to "emer",
        "ễmx" to "êmx", "ễme" to "ẽme", "êmxe" to "emxe", "ẽmex" to "emex",
        "ệmj" to "êmj", "ệme" to "ẹme", "êmje" to "emje", "ẹmej" to "emej",
        "ếns" to "êns", "ếne" to "éne", "ênse" to "ense", "énes" to "enes",
        "ềnf" to "ênf", "ềne" to "ène", "ênfe" to "enfe", "ènef" to "enef", 
        "ểnr" to "ênr", "ểne" to "ẻne", "ênre" to "enre", "ẻner" to "ener",
        "ễnx" to "ênx", "ễne" to "ẽne", "ênxe" to "enxe", "ẽnex" to "enex",
        "ệnj" to "ênj", "ệne" to "ẹne", "ênje" to "enje", "ẹnej" to "enej",
        "ếps" to "êps", "ếpe" to "épe", "êpse" to "epse", "épes" to "epes",
        "ệpj" to "êpj", "ệpe" to "ẹpe", "êpje" to "epje", "ẹpej" to "epej",
        "ếts" to "êts", "ếte" to "éte", "êtse" to "etes", "étes" to "etes",
        "ệtj" to "êtj", "ệte" to "ẹte", "êtje" to "etje", "ẹtej" to "etej",
        "ếchs" to "êchs", "ếche" to "éche", "êchse" to "eches", "éches" to "eches",
        "ệchj" to "êchj", "ệche" to "ẹche", "êchje" to "echje", "ẹchej" to "echej",
        "ếnhs" to "ênhs", "ếnhe" to "énhe", "ênhse" to "enhse", "énhes" to "enhes",
        "ềnhf" to "ênhf", "ềnhe" to "ènhe", "ênhfe" to "enhfe", "ènhef" to "enhef",
        "ểnhr" to "ênhr", "ểnhe" to "ẻnhe", "ênhre" to "enhre", "ẻnher" to "enher",
        "ễnhx" to "ênhx", "ễnhe" to "ẽnhe", "ênhxe" to "enhxe", "ẽnhex" to "enhex",
        "ệnhj" to "ênhj", "ệnhe" to "ẹnhe", "ênhje" to "enhje", "ẹnhej" to "enhej",

        "ôcs" to "ốc", "ôcj" to "ộc",
        "óco" to "ốc", "ọco" to "ộc",
        "ôis" to "ối", "ôif" to "ồi", "ôir" to "ổi", "ôix" to "ỗi", "ôij" to "ội",
        "óio" to "ối", "òio" to "ồi", "ỏio" to "ổi", "õio" to "ỗi", "ọio" to "ội",
        "ôms" to "ốm", "ômf" to "ồm", "ômr" to "ổm", "ômx" to "ỗm", "ômj" to "ộm",
        "ómo" to "ốm", "òmo" to "ồm", "ỏmo" to "ổm", "õmo" to "ỗm", "ọmo" to "ộm",
        "ôns" to "ốn", "ônf" to "ồn", "ônr" to "ổn", "ônx" to "ỗn", "ônj" to "ộn",
        "óno" to "ốn", "òno" to "ồn", "ỏno" to "ổn", "õno" to "ỗn", "ọno" to "ộn",
        "ôps" to "ốp", "ôpj" to "ộp",
        "ópo" to "ốp", "ọpo" to "ộp",
        "ôts" to "ốt", "ôtj" to "ột",
        "óto" to "ốt", "ọto" to "ột",
        "ôngs" to "ống", "ôngf" to "ồng", "ôngr" to "ổng", "ôngx" to "ỗng", "ôngj" to "ộng",
        "óngo" to "ống", "òngo" to "ồng", "ỏngo" to "ổng", "õngo" to "ỗng", "ọngo" to "ộng",

        "ốcs" to "ôcs", "ốco" to "óco", "ôcso" to "ocso", "ócos" to "ocos",       
        "ộcj" to "ôcj", "ộco" to "ọco", "ôcjo" to "ocjo", "ọcoj" to "ocoj",
        "ốis" to "ôis", "ốio" to "óio", "ôiso" to "oiso", "óios" to "oios",
        "ồif" to "ôif", "ồio" to "òio", "ôifo" to "oifo", "òiof" to "oiof",
        "ổir" to "ôir", "ổio" to "ỏio", "ôiro" to "oiro", "ỏior" to "oior",
        "ỗix" to "ôix", "ỗio" to "õio", "ôixo" to "oixo", "õiox" to "oiox",
        "ộij" to "ôij", "ộio" to "ọio", "ôijo" to "oijo", "ọioj" to "oioj",
        "ốms" to "ôms", "ốmo" to "ómo", "ômso" to "omso", "ómos" to "omos",
        "ồmf" to "ômf", "ồmo" to "òmo", "ômfo" to "omfo", "òmof" to "omof",
        "ổmr" to "ômr", "ổmo" to "ỏmo", "ômro" to "omro", "ỏmor" to "omor",
        "ỗmx" to "ômx", "ỗmo" to "õmo", "ômxo" to "omxo", "õmox" to "omox",
        "ộmj" to "ômj", "ộmo" to "ọmo", "ômjo" to "omjo", "ọmoj" to "omoj",
        "ốns" to "ôns", "ốno" to "óno", "ônso" to "onso", "ónos" to "onos",
        "ồnf" to "ônf", "ồno" to "òno", "ônfo" to "onfo", "ònof" to "onof",
        "ổnr" to "ônr", "ổno" to "ỏno", "ônro" to "onro", "ỏnor" to "onor",
        "ỗnx" to "ônx", "ỗno" to "õno", "ônxo" to "onxo", "õnox" to "onox",
        "ộnj" to "ônj", "ộno" to "ọno", "ônjo" to "onjo", "ọnoj" to "onoj",
        "ốps" to "ôps", "ốpo" to "ópo", "ôpso" to "opso", "ópos" to "opos",       
        "ộpj" to "ôpj", "ộpo" to "ọpo", "ôpjo" to "opjo", "ọpoj" to "opoj",
        "ốts" to "ôts", "ốto" to "óto", "ôtso" to "otso", "ótos" to "otos",       
        "ộtj" to "ôtj", "ộto" to "ọto", "ôtjo" to "otjo", "ọtoj" to "otoj",
        "ốngs" to "ôngs", "ốngo" to "óngo", "ôngso" to "ongso", "óngos" to "ongos",
        "ồngf" to "ôngf", "ồngo" to "òngo", "ôngfo" to "ongfo", "òngof" to "ongof",
        "ổngr" to "ôngr", "ổngo" to "ỏngo", "ôngro" to "ongro", "ỏngor" to "ongor",
        "ỗngx" to "ôngx", "ỗngo" to "õngo", "ôngxo" to "ongxo", "õngox" to "ongox",
        "ộngj" to "ôngj", "ộngo" to "ọngo", "ôngjo" to "ongjo", "ọngoj" to "ongoj",

        "ơis" to "ới", "ơif" to "ời", "ơir" to "ởi", "ơix" to "ỡi", "ơij" to "ợi",
        "óiw" to "ới", "òiw" to "ời", "ỏiw" to "ởi", "õiw" to "ỡi", "ọiw" to "ợi",
        "ơms" to "ớm", "ơmf" to "ờm", "ơmr" to "ởm", "ơmx" to "ỡm", "ơmj" to "ợm",
        "ómw" to "ớm", "òmw" to "ờm", "ỏmw" to "ởm", "õmw" to "ỡm", "ọmw" to "ợm",
        "ơns" to "ớn", "ơnf" to "ờn", "ơnr" to "ởn", "ơnx" to "ỡn", "ơnj" to "ợn",
        "ónw" to "ớn", "ònw" to "ờn", "ỏnw" to "ởn", "õnw" to "ỡn", "ọnw" to "ợn",
        "ơps" to "ớp", "ơpj" to "ợp",
        "ópw" to "ớp", "ọpw" to "ợp",
        "ơts" to "ớt", "ơtj" to "ợt",
        "ótw" to "ớt", "ọtw" to "ợt",

        "ớis" to "ơis", "ớiw" to "óiw", "ơisw" to "oisw", "óiws" to "oiws",
        "ờif" to "ơif", "ờiw" to "òiw", "ơifw" to "oifw", "òiwf" to "oiwf",
        "ởir" to "ơir", "ởiw" to "ỏiw", "ơirw" to "oirw", "ỏiwr" to "oiwr",
        "ỡix" to "ơix", "ỡiw" to "õiw", "ơixw" to "oixw", "õiwx" to "oiwx",
        "ợij" to "ơij", "ợiw" to "ọiw", "ơijw" to "oijw", "ọiwj" to "oiwj",
        "ớms" to "ơms", "ớmw" to "ómw", "ơmsw" to "omsw", "ómws" to "omws",
        "ờmf" to "ơmf", "ờmw" to "òmw", "ơmfw" to "omfw", "òmwf" to "omwf",
        "ởmr" to "ơmr", "ởmw" to "ỏmw", "ơmrw" to "omrw", "ỏmwr" to "omwr",
        "ỡmx" to "ơmx", "ỡmw" to "õmw", "ơmxw" to "omxw", "õmwx" to "omwx",
        "ợmj" to "ơmj", "ợmw" to "ọmw", "ơmjw" to "omjw", "ọmwj" to "omwj",
        "ớns" to "ơns", "ớnw" to "ónw", "ơnsw" to "onsw", "ónws" to "onws",
        "ờnf" to "ơnf", "ờnw" to "ònw", "ơnfw" to "onfw", "ònwf" to "onwf",
        "ởnr" to "ơnr", "ởnw" to "ỏnw", "ơnrw" to "onrw", "ỏnwr" to "onwr",
        "ỡnx" to "ơnx", "ỡnw" to "õnw", "ơnxw" to "onxw", "õnwx" to "onwx",
        "ợnj" to "ơnj", "ợnw" to "ọnw", "ơnjw" to "onjw", "ọnwj" to "onwj",
        "ớps" to "ơps", "ớpw" to "ópw", "ơpsw" to "opsw", "ópws" to "opws",       
        "ợpj" to "ơpj", "ợpw" to "ọpw", "ơpjw" to "opjw", "ọpwj" to "opwj",
        "ớts" to "ơts", "ớtw" to "ótw", "ơtsw" to "otsw", "ótws" to "otws",       
        "ợtj" to "ơtj", "ợtw" to "ọtw", "ơtjw" to "otjw", "ọtwj" to "otwj",

        "ưas" to "ứa", "ưaf" to "ừa", "ưar" to "ửa", "ưax" to "ữa", "ưaj" to "ựa",
        "úaw" to "ứa", "ùaw" to "ừa", "ủaw" to "ửa", "ũaw" to "ữa", "ụaw" to "ựa",
        "ưcs" to "ức", "ưcj" to "ực",
        "úcw" to "ức", "ụcw" to "ực",
        "ưis" to "ứi", "ưif" to "ừi", "ưir" to "ửi", "ưix" to "ữi", "ưij" to "ựi",
        "úiw" to "ứi", "ùiw" to "ừi", "ủiw" to "ửi", "ũiw" to "ữi", "ụiw" to "ựi",
        "ưms" to "ứm", "ưmf" to "ừm", "ưmr" to "ửm", "ưmx" to "ữm", "ưmj" to "ựm",
        "úmw" to "ứm", "ùmw" to "ừm", "ủmw" to "ửm", "ũmw" to "ữm", "ụmw" to "ựm",
        "ưns" to "ứn", "ưnf" to "ừn", "ưnr" to "ửn", "ưnx" to "ữn", "ưnj" to "ựn",
        "únw" to "ứn", "ùnw" to "ừn", "ủnw" to "ửn", "ũnw" to "ữn", "ụnw" to "ựn",
        "ưts" to "ứt", "ưtj" to "ựt",
        "útw" to "ứt", "ụtw" to "ựt",
        "ưus" to "ứu", "ưuf" to "ừu", "ưur" to "ửu", "ưux" to "ữu", "ưuj" to "ựu",
        "úuw" to "ứu", "ùuw" to "ừu", "ủuw" to "ửu", "ũuw" to "ữu", "ụuw" to "ựu",
        "ưngs" to "ứng", "ưngf" to "ừng", "ưngr" to "ửng", "ưngx" to "ững", "ưngj" to "ựng",
        "úngw" to "ứng", "ùngw" to "ừng", "ủngw" to "ửng", "ũngw" to "ững", "ụngw" to "ựng",

        "ứas" to "ưas", "ứaw" to "úaw", "ưasw" to "uasw", "úaws" to "uaws",
        "ừaf" to "ưaf", "ừaw" to "ùaw", "ưafw" to "uafw", "ùawf" to "uawf",
        "ửar" to "ưar", "ửaw" to "ủaw", "ưarw" to "uarw", "ủawr" to "uawr",
        "ữax" to "ưax", "ữaw" to "ũaw", "ưaxw" to "uaxw", "ũawx" to "uawx",
        "ựaj" to "ưaj", "ựaw" to "ụaw", "ưajw" to "uajw", "ụawj" to "uawj",
        "ứcs" to "ưcs", "ứcw" to "úcw", "ưcsw" to "ucsw", "úcws" to "ucws",        
        "ựcj" to "ưcj", "ựcw" to "ụcw", "ưcjw" to "ucjw", "ụcwj" to "ucwj",
        "ứis" to "ưis", "ứiw" to "úiw", "ưisw" to "uisw", "úiws" to "uiws",
        "ừif" to "ưif", "ừiw" to "ùiw", "ưifw" to "uifw", "ùiwf" to "uiwf",
        "ửir" to "ưir", "ửiw" to "ủiw", "ưirw" to "uirw", "ủiwr" to "uiwr",
        "ữix" to "ưix", "ữiw" to "ũiw", "ưixw" to "uixw", "ũiwx" to "uiwx",
        "ựij" to "ưij", "ựiw" to "ụiw", "ưijw" to "uijw", "ụiwj" to "uiwj",
        "ứms" to "ưms", "ứmw" to "úmw", "ưmsw" to "umsw", "úmws" to "umws",
        "ừmf" to "ưmf", "ừmw" to "ùmw", "ưmfw" to "umfw", "ùmwf" to "umwf",
        "ửmr" to "ưmr", "ửmw" to "ủmw", "ưmrw" to "umrw", "ủmwr" to "umwr",
        "ữmx" to "ưmx", "ữmw" to "ũmw", "ưmxw" to "umxw", "ũmwx" to "umwx",
        "ựmj" to "ưmj", "ựmw" to "ụmw", "ưmjw" to "umjw", "ụmwj" to "umwj",
        "ứns" to "ưns", "ứnw" to "únw", "ưnsw" to "unsw", "únws" to "unws",
        "ừnf" to "ưnf", "ừnw" to "ùnw", "ưnfw" to "unfw", "ùnwf" to "unwf",
        "ửnr" to "ưnr", "ửnw" to "ủnw", "ưnrw" to "unrw", "ủnwr" to "unwr",
        "ữnx" to "ưnx", "ữnw" to "ũnw", "ưnxw" to "unxw", "ũnwx" to "unwx",
        "ựnj" to "ưnj", "ựnw" to "ụnw", "ưnjw" to "unjw", "ụnwj" to "unwj",
        "ứts" to "ưts", "ứtw" to "útw", "ưtsw" to "utsw", "útws" to "utws",        
        "ựtj" to "ưtj", "ựtw" to "ụtw", "ưtjw" to "utjw", "ụtwj" to "utwj",
        "ứus" to "ưus", "ứuw" to "úuw", "ưusw" to "uusw", "úuws" to "uuws",
        "ừuf" to "ưuf", "ừuw" to "ùuw", "ưufw" to "uufw", "ùuwf" to "uuwf",
        "ửur" to "ưur", "ửuw" to "ủuw", "ưurw" to "uurw", "ủuwr" to "uuwr",
        "ữux" to "ưux", "ữuw" to "ũuw", "ưuxw" to "uuxw", "ũuwx" to "uuwx",
        "ựuj" to "ưuj", "ựuw" to "ụuw", "ưujw" to "uujw", "ụuwj" to "uuwj",
        "ứngs" to "ưngs", "ứngw" to "úngw", "ưngsw" to "ungsw", "úngws" to "ungws",
        "ừngf" to "ưngf", "ừngw" to "ùngw", "ưngfw" to "ungfw", "ùngwf" to "ungwf",
        "ửngr" to "ưngr", "ửngw" to "ủngw", "ưngrw" to "ungrw", "ủngwr" to "ungwr",
        "ữngx" to "ưngx", "ữngw" to "ũngw", "ưngxw" to "ungxw", "ũngwx" to "ungwx",
        "ựngj" to "ưngj", "ựngw" to "ụngw", "ưngjw" to "ungjw", "ụngwj" to "ungwj",

        "iems" to "iém", "iemf" to "ièm", "iemr" to "iẻm", "iemx" to "iẽm", "iemj" to "iẹm",
        "iéme" to "iếm", "ième" to "iềm", "iẻme" to "iểm", "iẽme" to "iễm", "iẹme" to "iệm",
        "iêms" to "iếm", "iêmf" to "iềm", "iêmr" to "iểm", "iêmx" to "iễm", "iêmj" to "iệm",
        "iens" to "ién", "ienf" to "ièn", "ienr" to "iẻn", "ienx" to "iẽn", "ienj" to "iẹn",
        "iéne" to "iến", "iène" to "iền", "iẻne" to "iển", "iẽne" to "iễn", "iẹne" to "iện",
        "iêns" to "iến", "iênf" to "iền", "iênr" to "iển", "iênx" to "iễn", "iênj" to "iện",
        "ieps" to "iép", "iepj" to "iẹp",
        "iépe" to "iếp", "iẹpe" to "iệp",
        "iêps" to "iếp", "iêpj" to "iệp",
        "iets" to "iét", "ietj" to "iẹt",
        "iéte" to "iết", "iẹte" to "iệt",
        "iêts" to "iết", "iêtj" to "iệt",
        "ieus" to "iéu", "ieuf" to "ièu", "ieur" to "iẻu", "ieux" to "iẽu", "ieuj" to "iẹu",
        "iéue" to "iếu", "ièue" to "iều", "iẻue" to "iểu", "iẽue" to "iễu", "iẹue" to "iệu",
        "iêus" to "iếu", "iêuf" to "iều", "iêur" to "iểu", "iêux" to "iễu", "iêuj" to "iệu",
        "iengs" to "iéng", "iengf" to "ièng", "iengr" to "iẻng", "iengx" to "iẽng", "iengj" to "iẹng",
        "iénge" to "iếng", "iènge" to "iềng", "iẻnge" to "iểng", "iẽnge" to "iễng", "iẹnge" to "iệng",
        "iêngs" to "iếng", "iêngf" to "iềng", "iêngr" to "iểng", "iêngx" to "iễng", "iêngj" to "iệng",

        "iếs" to "iês", "iếe" to "iée", "iêse" to "iese", "iées" to "iees",
        "iềf" to "iêf", "iềe" to "ièe", "iêfe" to "iefe", "ièef" to "ieef",
        "iểr" to "iêr", "iểe" to "iẻe", "iêre" to "iere", "iẻer" to "ieer",
        "iễx" to "iêx", "iễe" to "iẽe", "iêxe" to "iexe", "iẽex" to "ieex",
        "iệj" to "iêj", "iệe" to "iẹe", "iêje" to "ieje", "iẹej" to "ieej",
        "iếms" to "iêms", "iếme" to "iéme", "iêmse" to "iemse", "iémes" to "iemes",
        "iềmf" to "iêmf", "iềme" to "ième", "iêmfe" to "iemfe", "ièmef" to "iemef",
        "iểmr" to "iêmr", "iểme" to "iẻme", "iêmre" to "iemre", "iẻmer" to "iemer",
        "iễmx" to "iêmx", "iễme" to "iẽme", "iêmxe" to "iemxe", "iẽmex" to "iemex",
        "iệmj" to "iêmj", "iệme" to "iẹme", "iêmje" to "iemje", "iẹmej" to "iemej",
        "iếns" to "iêns", "iếne" to "iéne", "iênse" to "iense", "iénes" to "ienes",
        "iềnf" to "iênf", "iềne" to "iène", "iênfe" to "ienfe", "iènef" to "ienef",
        "iểnr" to "iênr", "iểne" to "iẻne", "iênre" to "ienre", "iẻner" to "iener",
        "iễnx" to "iênx", "iễne" to "iẽne", "iênxe" to "ienxe", "iẽnex" to "ienex",
        "iệnj" to "iênj", "iệne" to "iẹne", "iênje" to "ienje", "iẹnej" to "ienej",
        "iếps" to "iêps", "iếpe" to "iépe", "iêpse" to "iepse", "iépes" to "iepes",
        "iệpj" to "iêpj", "iệpe" to "iẹpe", "iêpje" to "iepje", "iẹpej" to "iepej",
        "iếts" to "iêts", "iếte" to "iéte", "iêtse" to "ietse", "iétes" to "ietes",
        "iệtj" to "iêtj", "iệte" to "iẹte", "iêtje" to "ietje", "iẹtej" to "ietej",
        "iếus" to "iêus", "iếue" to "iéue", "iêuse" to "ieuse", "iéues" to "ieues",
        "iềuf" to "iêuf", "iềue" to "ièue", "iêufe" to "ieufe", "ièuef" to "ieuef",
        "iểur" to "iêur", "iểue" to "iẻue", "iêure" to "ieure", "iẻuer" to "ieuer",
        "iễux" to "iêux", "iễue" to "iẽue", "iêuxe" to "ieuxe", "iẽuex" to "ieuex",
        "iệuj" to "iêuj", "iệue" to "iẹue", "iêuje" to "ieuje", "iẹuej" to "ieuej",
        "iếngs" to "iêngs", "iếnge" to "iénge", "iêngse" to "iengse", "iénges" to "ienges",
        "iềngf" to "iêngf", "iềnge" to "iènge", "iêngfe" to "iengfe", "ièngef" to "iengef",
        "iểngr" to "iêngr", "iểnge" to "iẻnge", "iêngre" to "iengre", "iẻnger" to "ienger",
        "iễngx" to "iêngx", "iễnge" to "iẽnge", "iêngxe" to "iengxe", "iẽngex" to "iengex",
        "iệngj" to "iêngj", "iệnge" to "iẹnge", "iêngje" to "iengje", "iẹngej" to "iengej",

        "uyens" to "uyén", "uyenf" to "uyèn", "uyenr" to "uyẻn", "uyenx" to "uyẽn", "uyenj" to "uyẹn",
        "uyéne" to "uyến", "uyène" to "uyền", "uyẻne" to "uyển", "uyẽne" to "uyễn", "uyẹne" to "uyện",
        "uyêns" to "uyến", "uyênf" to "uyền", "uyênr" to "uyển", "uyênx" to "uyễn", "uyênj" to "uyện",
        "uyets" to "uyét", "uyetf" to "uyèt", "uyetr" to "uyẻt", "uyetx" to "uyẽt", "uyetj" to "uyẹt",
        "uyéte" to "uyết", "uyète" to "uyềt", "uyẻte" to "uyểt", "uyẽte" to "uyễt", "uyẹte" to "uyệt",
        "uyêts" to "uyết", "uyêtf" to "uyềt", "uyêtr" to "uyểt", "uyêtx" to "uyễt", "uyêtj" to "uyệt",

        "uyếns" to "uyêns", "uyếne" to "uyéne", "uyênse" to "uyense", "uyénes" to "uyenes",
        "uyềnf" to "uyênf", "uyềne" to "uyène", "uyênfe" to "uyenfe", "uyènef" to "uyenef",
        "uyểnr" to "uyênr", "uyểne" to "uyẻne", "uyênre" to "uyenre", "uyẻner" to "uyener",
        "uyễnx" to "uyênx", "uyễne" to "uyẽne", "uyênxe" to "uyenxe", "uyẽnex" to "uyenex",
        "uyệnj" to "uyênj", "uyệne" to "uyẹne", "uyênje" to "uyenje", "uyẹnej" to "uyenej",
        "uyếts" to "uyêts", "uyếte" to "uyéte", "uyêtse" to "uyetse", "uyétes" to "uyetes",
        "uyềtf" to "uyêtf", "uyềte" to "uyète", "uyêtfe" to "uyetfe", "uyètef" to "uyetef",
        "uyểtr" to "uyêtr", "uyểte" to "uyẻte", "uyêtre" to "uyetre", "uyẻter" to "uyeter",
        "uyễtx" to "uyêtx", "uyễte" to "uyẽte", "uyêtxe" to "uyetxe", "uyẽtex" to "uyetex",
        "uyệtj" to "uyêtj", "uyệte" to "uyẹte", "uyêtje" to "uyetje", "uyẹtej" to "uyetej",

        "uyts" to "uýt", "uytj" to "uỵt",
        "uynhs" to "uýnh", "uynhf" to "uỳnh", "uynhr" to "uỷnh", "uynhx" to "uỹnh", "uynhj" to "uỵnh",

        "uýts" to "uyts", "uỵtj" to "uytj",
        "uýnhs" to "uynhs", "uỳnhf" to "uynhf", "uỷnhr" to "uynhr", "uỹnh" to "uynhx", "uỵnhj" to "uynhj",
        
        "uits" to "uít", "uitj" to "uịt",

        "uíts" to "uits", "uịtj" to "uitj",

        "uos" to "úo", "uof" to "ùo", "uor" to "ủo", "uox" to "ũo", "uoj" to "ụo",
        "úoc" to "uóc", "ụoc" to "uọc",
        "uocs" to "uóc", "uocj" to "uọc",
        "uócw" to "ước", "uọcw" to "ược",
        "ươcs" to "ước", "ươcj" to "ược",
        "úoi" to "uói", "ùoi"  to "uòi", "ủoi" to "uỏi", "ũoi" to "uõi", "ụoi" to "uọi",
        "uois" to "uói", "uoif" to "uòi", "uoir" to "uỏi", "uoix" to "uõi", "uoij" to "uọi",
        "uóiw" to "ưới", "uòiw" to "ười", "uỏiw" to "ưởi", "uõiw" to "ưỡi", "uọiw" to "ượi",
        "ươis" to "ưới", "ươif" to "ười", "ươir" to "ưởi", "ươix" to "ưỡi", "ươij" to "ượi",
        "úom" to "uóm", "ùom"  to "uòm", "ủom" to "uỏm", "ũom" to "uõm", "ụom" to "uọm",
        "uoms" to "uóm", "uomf" to "uòm", "uomr" to "uỏm", "uomx" to "uõm", "uomj" to "uọm",
        "uómw" to "ướm", "uòmw" to "ườm", "uỏmw" to "ưởm", "uõmw" to "ưỡm", "uọmw" to "ượm",
        "ươms" to "ướm", "ươmf" to "ườm", "ươmr" to "ưởm", "ươmx" to "ưỡm", "ươmj" to "ượm",
        "úon" to "uón", "ùon"  to "uòn", "ủon" to "uỏn", "ũon" to "uõn", "ụon" to "uọn",
        "uons" to "uón", "uonf" to "uòn", "uonr" to "uỏn", "uonx" to "uõn", "uonj" to "uọn",
        "uónw" to "ướn", "uònw" to "ườn", "uỏnw" to "ưởn", "uõnw" to "ưỡn", "uọnw" to "ượn",
        "ươns" to "ướn", "ươnf" to "ườn", "ươnr" to "ưởn", "ươnx" to "ưỡn", "ươnj" to "ượn",
        "úop" to "uóp", "ụop" to "uọp",
        "uops" to "uóp", "uopj" to "uọp",
        "uópw" to "ướp", "uọpw" to "ượp",
        "ươps" to "ướp", "ươpj" to "ượp",
        "úot" to "uót", "ụot" to "uọt",
        "uots" to "uót", "uotj" to "uọt",
        "uótw" to "ướt", "uọtw" to "ượt",
        "ươts" to "ướt", "ươtj" to "ượt",
        "úou" to "uóu", "ùou"  to "uòu", "ủou" to "uỏu", "ũou" to "uõu", "ụou" to "uọu",
        "uous" to "uóu", "uouf" to "uòu", "uour" to "uỏu", "uoux" to "uõu", "uouj" to "uọu",
        "uóuw" to "ướu", "uòuw" to "ườu", "uỏuw" to "ưởu", "uõuw" to "ưỡu", "uọuw" to "ượu",
        "ươus" to "ướu", "ươuf" to "ườu", "ươur" to "ưởu", "ươux" to "ưỡu", "ươuj" to "ượu",
        "úong" to "uóng", "ùong"  to "uòng", "ủong" to "uỏng", "ũong" to "uõng", "ụong" to "uọng",
        "uongs" to "uóng", "uongf" to "uòng", "uongr" to "uỏng", "uongx" to "uõng", "uongj" to "uọng",
        "uóngw" to "ướng", "uòngw" to "ường", "uỏngw" to "ưởng", "uõngw" to "ưỡng", "uọngw" to "ượng",
        "ươngs" to "ướng", "ươngf" to "ường", "ươngr" to "ưởng", "ươngx" to "ưỡng", "ươngj" to "ượng",

        "úos" to "uos", "ùof" to "uof", "ủor" to "uor", "ũo" to "uox", "ụoj" to "uoj",
        "uócs" to "uocs", "uọcj" to "uocj",
        "ướcs" to "ươcs", "ướcw" to "uócw", "ươcsw" to "uocsw", "uócws" to "uocws",
        "ượcj" to "ươcj", "ượcw" to "uọcw", "ươcjw" to "uocjw", "uọcwj" to "uocwj",
        "uóis" to "uois", "uòif" to "uoif", "uỏir" to "uoir", "uõix" to "uoix", "uọij" to "uoij",
        "ướis" to "ươis", "ướiw" to "uóiw", "ươisw" to "uoisw", "uóiws" to "uoiws",
        "ườif" to "ươif", "ườiw" to "uòiw", "ươifw" to "uoifw", "uòiwf" to "uoiwf", 
        "ưởir" to "ươir", "ưởiw" to "uỏiw", "ươirw" to "uoirw", "uỏiwr" to "uoiwr", 
        "ưỡix" to "ươix", "ưỡiw" to "uõiw", "ươixw" to "uoixw", "uõiwx" to "uoiwx", 
        "ượij" to "ươij", "ượiw" to "uóiw", "ươijw" to "uoijw", "uọiwj" to "uoiwj",
        "uóms" to "uoms", "uòmf" to "uomf", "uỏmr" to "uomr", "uõmx" to "uomx", "uọmj" to "uomj",
        "ướms" to "ươms", "ướmw" to "uómw", "ươmsw" to "uomsw", "uómws" to "uomws",
        "ườmf" to "ươmf", "ườmw" to "uòmw", "ươmfw" to "uomfw", "uòmwf" to "uomwf", 
        "ưởmr" to "ươmr", "ưởmw" to "uỏmw", "ươmrw" to "uomrw", "uỏmwr" to "uomwr", 
        "ưỡmx" to "ươmx", "ưỡmw" to "uõmw", "ươmxw" to "uomxw", "uõmwx" to "uomwx", 
        "ượmj" to "ươmj", "ượmw" to "uómw", "ươmjw" to "uomjw", "uọmwj" to "uomwj",
        "uóns" to "uons", "uònf" to "uonf", "uỏnr" to "uonr", "uõnx" to "uonx", "uọnj" to "uonj",
        "ướns" to "ươns", "ướnw" to "uónw", "ươnsw" to "uonsw", "uónws" to "uonws",
        "ườnf" to "ươnf", "ườnw" to "uònw", "ươnfw" to "uonfw", "uònwf" to "uonwf", 
        "ưởnr" to "ươnr", "ưởnw" to "uỏnw", "ươnrw" to "uonrw", "uỏnwr" to "uonwr", 
        "ưỡnx" to "ươnx", "ưỡnw" to "uõnw", "ươnxw" to "uonxw", "uõnwx" to "uonwx", 
        "ượnj" to "ươnj", "ượnw" to "uónw", "ươnjw" to "uonjw", "uọnwj" to "uonwj",
        "uóps" to "uops", "uọpj" to "uopj",
        "ướps" to "ươps", "ướpw" to "uópw", "ươpsw" to "uopsw", "uópws" to "uopws",
        "ượpj" to "ươpj", "ượpw" to "uọpw", "ươpjw" to "uopjw", "uọpwj" to "uopwj",
        "uóts" to "uots", "uọtj" to "uotj",
        "ướts" to "ươts", "ướtw" to "uótw", "ươtsw" to "uotsw", "uótws" to "uotws",
        "ượtj" to "ươtj", "ượtw" to "uọtw", "ươtjw" to "uotjw", "uọtwj" to "uotwj",
        "uóus" to "uous", "uòuf" to "uouf", "uỏur" to "uour", "uõux" to "uoux", "uọuj" to "uouj",
        "ướus" to "ươus", "ướuw" to "uóuw", "ươusw" to "uousw", "uóuws" to "uouws",
        "ườuf" to "ươuf", "ườuw" to "uòuw", "ươufw" to "uoufw", "uòuwf" to "uouwf", 
        "ưởur" to "ươur", "ưởuw" to "uỏuw", "ươurw" to "uourw", "uỏuwr" to "uouwr", 
        "ưỡux" to "ươux", "ưỡuw" to "uõuw", "ươuxw" to "uouxw", "uõuwx" to "uouwx", 
        "ượuj" to "ươuj", "ượuw" to "uóuw", "ươujw" to "uoujw", "uọuwj" to "uouwj",
        "uóngs" to "uongs", "uòngf" to "uongf", "uỏngr" to "uongr", "uõngx" to "uongx", "uọngj" to "uongj",
        "ướngs" to "ươngs", "ướngw" to "uóngw", "ươngsw" to "uongsw", "uóngws" to "uongws",
        "ườngf" to "ươngf", "ườngw" to "uòngw", "ươngfw" to "uongfw", "uòngwf" to "uongwf", 
        "ưởngr" to "ươngr", "ưởngw" to "uỏngw", "ươngrw" to "uongrw", "uỏngwr" to "uongwr", 
        "ưỡngx" to "ươngx", "ưỡngw" to "uõngw", "ươngxw" to "uongxw", "uõngwx" to "uongwx", 
        "ượngj" to "ươngj", "ượngw" to "uóngw", "ươngjw" to "uongjw", "uọngwj" to "uongwj",

        "uóco" to "uốc", "uọco" to "uộc",
        "uôcs" to "uốc", "uôcj" to "uộc",
        "uóio" to "uối", "uòio" to "uồi", "uỏio" to "uổi", "uõio" to "uỗi", "uọio" to "uội",
        "uôis" to "uối", "uôif" to "uồi", "uôir" to "uổi", "uôix" to "uỗi", "uôij" to "uội",
        "uómo" to "uốm", "uòmo" to "uồm", "uỏmo" to "uổm", "uõmo" to "uỗm", "uọmo" to "uộm",
        "uôms" to "uốm", "uômf" to "uồm", "uômr" to "uổm", "uômx" to "uỗm", "uômj" to "uộm",
        "uóno" to "uốn", "uòno" to "uồn", "uỏno" to "uổn", "uõno" to "uỗn", "uọno" to "uộn",
        "uôns" to "uốn", "uônf" to "uồn", "uônr" to "uổn", "uônx" to "uỗn", "uônj" to "uộn",
        "uópo" to "uốp", "uọpo" to "uộp",
        "uôps" to "uốp", "uôpj" to "uộp",
        "uóto" to "uốt", "uọto" to "uột",
        "uôts" to "uốt", "uôtj" to "uột",
        "uóuo" to "uốu", "uòuo" to "uồu", "uỏuo" to "uổu", "uõuo" to "uỗu", "uọuo" to "uộu",
        "uôus" to "uốu", "uôuf" to "uồu", "uôur" to "uổu", "uôux" to "uỗu", "uôuj" to "uộu",
        "uóngo" to "uống", "uòngo" to "uồng", "uỏngo" to "uổng", "uõngo" to "uỗng", "uọngo" to "uộng",
        "uôngs" to "uống", "uôngf" to "uồng", "uôngr" to "uổng", "uôngx" to "uỗng", "uôngj" to "uộng",

        "uốcs" to "uôcs", "uốco" to "uóco", "uôcso" to "uocso", "uócos" to "uocos",
        "uộcj" to "uôcj", "uộco" to "uọco", "uôcjo" to "uocjo", "uọcoj" to "uocoj",
        "uốis" to "uôis", "uốio" to "uóio", "uôiso" to "uoiso", "uóios" to "uoios",
        "uồif" to "uôif", "uồio" to "uòio", "uôifo" to "uoifo", "uòiof" to "uoiof", 
        "uổir" to "uôir", "uổio" to "uỏio", "uôiro" to "uoiro", "uỏior" to "uoior", 
        "uỗix" to "uôix", "uỗio" to "uõio", "uôixo" to "uoixo", "uõiox" to "uoiox", 
        "uộij" to "uôij", "uộio" to "uóio", "uôijo" to "uoijo", "uọioj" to "uoioj",
        "uốms" to "uôms", "uốmo" to "uómo", "uômso" to "uomso", "uómos" to "uomos",
        "uồmf" to "uômf", "uồmo" to "uòmo", "uômfo" to "uomfo", "uòmof" to "uomof", 
        "uổmr" to "uômr", "uổmo" to "uỏmo", "uômro" to "uomro", "uỏmor" to "uomor", 
        "uỗmx" to "uômx", "uỗmo" to "uõmo", "uômxo" to "uomxo", "uõmox" to "uomox", 
        "uộmj" to "uômj", "uộmo" to "uómo", "uômjo" to "uomjo", "uọmoj" to "uomoj",
        "uốns" to "uôns", "uốno" to "uóno", "uônso" to "uonso", "uónos" to "uonos",
        "uồnf" to "uônf", "uồno" to "uòno", "uônfo" to "uonfo", "uònof" to "uonof", 
        "uổnr" to "uônr", "uổno" to "uỏno", "uônro" to "uonro", "uỏnor" to "uonor", 
        "uỗnx" to "uônx", "uỗno" to "uõno", "uônxo" to "uonxo", "uõnox" to "uonox", 
        "uộnj" to "uônj", "uộno" to "uóno", "uônjo" to "uonjo", "uọnoj" to "uonoj",
        "uốps" to "uôps", "uốpo" to "uópo", "uôpso" to "uopso", "uópos" to "uopos",
        "uộpj" to "uôpj", "uộpo" to "uọpo", "uôpjo" to "uopjo", "uọpoj" to "uopoj",
        "uốts" to "uôts", "uốto" to "uóto", "uôtso" to "uotso", "uótos" to "uotos",
        "uộtj" to "uôtj", "uộto" to "uọto", "uôtjo" to "uotjo", "uọtoj" to "uotoj",
        "uốus" to "uôus", "uốuo" to "uóuo", "uôuso" to "uouso", "uóuos" to "uouos",
        "uồuf" to "uôuf", "uồuo" to "uòuo", "uôufo" to "uoufo", "uòuof" to "uouof", 
        "uổur" to "uôur", "uổuo" to "uỏuo", "uôuro" to "uouro", "uỏuor" to "uouor", 
        "uỗux" to "uôux", "uỗuo" to "uõuo", "uôuxo" to "uouxo", "uõuox" to "uouox", 
        "uộuj" to "uôuj", "uộuo" to "uóuo", "uôujo" to "uoujo", "uọuoj" to "uouoj",
        "uốngs" to "uôngs", "uốngo" to "uóngo", "uôngso" to "uongso", "uóngos" to "uongos",
        "uồngf" to "uôngf", "uồngo" to "uòngo", "uôngfo" to "uongfo", "uòngof" to "uongof", 
        "uổngr" to "uôngr", "uổngo" to "uỏngo", "uôngro" to "uongro", "uỏngor" to "uongor", 
        "uỗngx" to "uôngx", "uỗngo" to "uõngo", "uôngxo" to "uongxo", "uõngox" to "uongox", 
        "uộngj" to "uôngj", "uộngo" to "uóngo", "uôngjo" to "uongjo", "uọngoj" to "uongoj",

        "yes" to "ýe", "yef" to "ỳe", "yer" to "ỷe", "yex" to "ỹe", "yej" to "ỵe",
        "ýem" to "yém", "ỳem" to "yèm", "ỷem" to "yẻm", "ỹem" to "yẽm", "ỵem" to "yẹm",
        "yems" to "yém", "yemf" to "yèm", "yemr" to "yẻm", "yemx" to "yẽm", "yemj" to "yẹm",
        "yêms" to "yếm", "yêmf" to "yềm", "yêmr" to "yểm", "yêmx" to "yễm", "yêmj" to "yệm",
        "yéme" to "yếm", "yème" to "yềm", "yẻme" to "yểm", "yẽme" to "yễm", "yẹme" to "yệm",
        "ýen" to "yén", "ỳen" to "yèn", "ỷen" to "yẻn", "ỹen" to "yẽn", "ỵen" to "yẹn",
        "yens" to "yén", "yenf" to "yèn", "yenr" to "yẻn", "yenx" to "yẽn", "yenj" to "yẹn",
        "yêns" to "yến", "yênf" to "yền", "yênr" to "yển", "yênx" to "yễn", "yênj" to "yện",
        "yéne" to "yến", "yène" to "yền", "yẻne" to "yển", "yẽne" to "yễn", "yẹne" to "yện",
        "ýet" to "yét", "ỵet" to "yẹt",
        "yets" to "yét", "yetj" to "yẹt",
        "yêts" to "yết", "yêtj" to "yệt",
        "yéte" to "yết", "yẹte" to "yệt",
        "ýeu" to "yéu", "ỳeu" to "yèu", "ỷeu" to "yẻu", "ỹeu" to "yẽu", "ỵeu" to "yẹu",
        "yeus" to "yéu", "yeuf" to "yèu", "yeur" to "yẻu", "yeux" to "yẽu", "yeuj" to "yẹu",
        "yêus" to "yếu", "yêuf" to "yều", "yêur" to "yểu", "yêux" to "yễu", "yêuj" to "yệu",
        "yéue" to "yếu", "yèue" to "yều", "yẻue" to "yểu", "yẽue" to "yễu", "yẹue" to "yệu",
        "ýeng" to "yéng", "ỳeng" to "yèng", "ỷeng" to "yẻng", "ỹeng" to "yẽng", "ỵeng" to "yẹng",
        "yengs" to "yéng", "yengf" to "yèng", "yengr" to "yẻng", "yengx" to "yẽng", "yengj" to "yẹng",
        "yêngs" to "yếng", "yêngf" to "yềng", "yêngr" to "yểng", "yêngx" to "yễng", "yêngj" to "yệng",
        "yénge" to "yếng", "yènge" to "yềng", "yẻnge" to "yểng", "yẽnge" to "yễng", "yẹnge" to "yệng",
        
        "ýes" to "yes", "ỳef" to "yef", "ỷer" to "yer", "ỹex" to "yex", "ỵej" to "yej",
        "yếms" to "yêms", "yếme" to "yéme", "yêmse" to "yemse", "yémes" to "yemes",
        "yềmf" to "yêmf", "yềme" to "yème", "yêmfe" to "yemfe", "yèmef" to "yemef",
        "yểmr" to "yêmr", "yểme" to "yẻme", "yêmre" to "yemre", "yẻmer" to "yemer",
        "yễmx" to "yêmx", "yễme" to "yẽme", "yêmxe" to "yemxe", "yẽmex" to "yemex",
        "yệmj" to "yêmj", "yệme" to "yẹme", "yêmje" to "yemje", "yẹmej" to "yemej",
        "yếns" to "yêns", "yếne" to "yéne", "yênse" to "yense", "yénes" to "yenes",
        "yềnf" to "yênf", "yềne" to "yène", "yênfe" to "yenfe", "yènef" to "yenef",
        "yểnr" to "yênr", "yểne" to "yẻne", "yênre" to "yenre", "yẻner" to "yener",
        "yễnx" to "yênx", "yễne" to "yẽne", "yênxe" to "yenxe", "yẽnex" to "yenex",
        "yệnj" to "yênj", "yệne" to "yẹne", "yênje" to "yenje", "yẹnej" to "yenej",
        "yếts" to "yêts", "yếte" to "yéte", "yêtse" to "yetse", "yétes" to "yetes",        
        "yệtj" to "yêtj", "yệte" to "yẹte", "yêtje" to "yetje", "yẹtej" to "yetej",
        "yếus" to "yêus", "yếue" to "yéue", "yêuse" to "yeuse", "yéues" to "yeues",
        "yềuf" to "yêuf", "yềue" to "yèue", "yêufe" to "yeufe", "yèuef" to "yeuef",
        "yểur" to "yêur", "yểue" to "yẻue", "yêure" to "yeure", "yẻuer" to "yeuer",
        "yễux" to "yêux", "yễue" to "yẽue", "yêuxe" to "yeuxe", "yẽuex" to "yeuex",
        "yệuj" to "yêuj", "yệue" to "yẹue", "yêuje" to "yeuje", "yẹuej" to "yeuej",
        "yếngs" to "yêngs", "yếnge" to "yénge", "yêngse" to "yengse", "yénges" to "yenges",
        "yềngf" to "yêngf", "yềnge" to "yènge", "yêngfe" to "yengfe", "yèngef" to "yengef",
        "yểngr" to "yêngr", "yểnge" to "yẻnge", "yêngre" to "yengre", "yẻnger" to "yenger",
        "yễngx" to "yêngx", "yễnge" to "yẽnge", "yêngxe" to "yengxe", "yẽngex" to "yengex",
        "yệngj" to "yêngj", "yệnge" to "yẹnge", "yêngje" to "yengje", "yẹngej" to "yengej", // Xử lý các trường hợp gõ sai chữ hoa (ví dụ: Shift + chữ, sau đó gõ dấu)
        "Aw" to "Ă", "Aw" to "Ă", "Aw" to "Ă",
        "Ow" to "Ơ", "Ow" to "Ơ", "Ow" to "Ơ",
        "Uw" to "Ư", "Uw" to "Ư", "Uw" to "Ư",
        "Ee" to "Ê", "Ee" to "Ê","Ee" to "Ê",
        "Oo" to "Ô", "Oo" to "Ô", "Oo" to "Ô",
        "Aa" to "Â", "Aa" to "Â", "Aa" to "Â",
        "Dd" to "Đ", "Dd" to "Đ", "Dd" to "Đ",
        "As" to "Á", "As" to "Á", "As" to "Á",
        "Af" to "À", "Af" to "À", "Af" to "À",
        "Ar" to "Ả", "Ar" to "Ả", "Ar" to "Ả",
        "Ax" to "Ã", "Ax" to "Ã", "Ax" to "Ã",
        "Aj" to "Ạ", "Aj" to "Ạ", "Aj" to "Ạ",
        "Ăs" to "Ắ",
        "Ăf" to "Ằ",
        "Ăr" to "Ẳ",
        "Ăx" to "Ẵ",
        "Ăj" to "Ặ",
        "Âs" to "Ấ",
        "Âf" to "Ầ",
        "Âr" to "Ẩ",
        "Âx" to "Ẫ",
        "Âj" to "Ậ",
        "Es" to "É",
        "Ef" to "È",
        "Er" to "Ẻ",
        "Ex" to "Ẽ",
        "Ej" to "Ẹ",
        "Ês" to "Ế",
        "Êf" to "Ề",
        "Êr" to "Ể",
        "Êx" to "Ễ",
        "Êj" to "Ệ",
        "Is" to "Í",
        "If" to "Ì",
        "Ir" to "Ỉ",
        "Ix" to "Ĩ",
        "Ij" to "Ị",
        "Os" to "Ó",
        "Of" to "Ò",
        "Or" to "Ỏ",
        "Ox" to "Õ",
        "Oj" to "Ọ",
        "Ôs" to "Ố",
        "Ôf" to "Ồ",
        "Ôr" to "Ổ",
        "Ôx" to "Ỗ",
        "Oj" to "Ộ",
        "Ơs" to "Ớ",
        "Ơf" to "Ờ",
        "Ơr" to "Ở",
        "Ơx" to "Ỡ",
        "Ơj" to "Ợ",
        "Us" to "Ú",
        "Uf" to "Ù",
        "Ur" to "Ủ",
        "Ux" to "Ũ",
        "Uj" to "Ụ",
        "Ưs" to "Ứ",
        "Ưf" to "Ừ",
        "Ưr" to "Ử",
        "Ưx" to "Ữ",
        "Ưj" to "Ự",
        "Ys" to "Ý",
        "Yf" to "Ỳ",
        "Yr" to "Ỷ",
        "Yx" to "Ỹ",
        "Yj" to "Ỵ",
        "Dds" to "Đ",
        "Ddf" to "Đ",
        "Ddr" to "Đ",
        "Ddx" to "Đ",
        "Ddj" to "Đ",
        "Aă" to "Ă",
        "Aâ" to "Â",
        "Eê" to "Ê",
        "Oô" to "Ô",
        "Oơ" to "Ơ",
        "Uư" to "Ư",
        "ônh" to "ông",
        "muá" to "múa",
        "baun" to "bạn",
        "tùnh" to "tình",
        "khoknh" to "không",
        "hanj" to "hạnh",
        "khônh" to "không",
        "chs" to "chí",
        "nghic" to "nghĩ",
        "tfnh" to "tình",
        "nghxi" to "nghĩ",
        "ohúc" to "phúc",
        "xoá" to "xóa", "ásk" to "ask",
        "nghx" to "nghĩ",
        "Ásk" to "Ask",
        "cuả" to "của"
    )

    override fun getActions(precedingText: String, toInsert: String): Pair<Int, String> {
        // Kiểm tra nếu là tiếng Anh thì không áp dụng Telex
        if (isEnglishWord(precedingText + toInsert)) {
            return Pair(0, toInsert)
        }
        
        // Check if we have a rule that matches the combination of precedingText and toInsert
        val input = precedingText + toInsert
        for ((pattern, replacement) in diacriticRules) {
            if (input.endsWith(pattern)) {
                // Return the number of characters to delete from precedingText and the replacement
                return Pair(pattern.length - toInsert.length, replacement)
            }
        }
        // No rule matches, just append the character
        return Pair(0, toInsert)
    }
}